# Generated by Django 3.0.6 on 2021-05-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('image', models.URLField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('fasion', 'Fashion'), ('toys', 'Toys'), ('electronics', 'Electronics'), ('home', 'Home')], default='Other', max_length=25)),
                ('date_added', models.DateField()),
            ],
        ),
    ]
