# Generated by Django 3.0.6 on 2021-05-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('fasion', 'Fashion'), ('toys', 'Toys'), ('electronics', 'Electronics'), ('home', 'Home'), ('other', 'Other')], default='Other', max_length=25),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
